import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {sample,small} from '../src/examples.mjs';import {validateProject,structure,associations,parseProject,parseTSV} from '../src/core.mjs';import {exportFragment,exportHTML,toJSON} from '../src/export.mjs';
for(const axis of ['rows','columns']){
 test(`${axis}: add/remove retains existing values and stable IDs`,()=>{const before=validateProject(sample),after=structure(before,{axis,type:'add'});assert.equal(after[axis].length,before[axis].length+1);const restored=structure(after,{axis,type:'remove',index:after[axis].length-1});assert.deepEqual(restored,before);assert.deepEqual(sample,before);});
 test(`${axis}: move and reverse retains values and IDs`,()=>{const moved=structure(sample,{axis,type:'move',index:1,direction:1});assert.equal(moved[axis][2].id,sample[axis][1].id);const original=structure(moved,{axis,type:'move',index:2,direction:-1});assert.deepEqual(original,sample);});
 test(`${axis}: grouping enable/split/disable preserves value matrix`,()=>{let p=structure(small,{axis,type:'group'});p=structure(p,{axis,type:'group'});assert.deepEqual(p.rows,small.rows);assert.deepEqual(p.columns,small.columns);assert.deepEqual(structure(p,{axis,type:'ungroup'}),small);assert.throws(()=>structure(p,{axis,type:'group'}),/one entry/);});
 test(`${axis}: remove singleton group removes that group only`,()=>{let p=structure(small,{axis,type:'group'});p=structure(p,{axis,type:'group'});p=structure(p,{axis,type:'remove',index:0});assert.equal(p[axis==='rows'?'rowGroups':'columnGroups'].length,1);assert.equal(p[axis==='rows'?'rowGroups':'columnGroups'][0].span,1);});
 test(`${axis}: cannot move out of bounds or remove last entry`,()=>{assert.throws(()=>structure(sample,{axis,type:'move',index:0,direction:-1}));let p=small;while(p[axis].length>1)p=structure(p,{axis,type:'remove',index:0});assert.throws(()=>structure(p,{axis,type:'remove',index:0}));});
}
test('split associations use actual flat header IDs and omit caption-only group labels',()=>{const heads=associations(sample,'r3','c4','split');assert.deepEqual(heads.map(h=>h.id),['workshop-s-1-1-r-r3','workshop-s-1-1-c-c4']);const html=exportFragment(sample,'split');assert.ok(html.includes(`headers="${heads.map(h=>h.id).join(' ')}"`));assert.equal(heads.length,2);});
test('crossing group boundary changes group association while retaining row identity',()=>{const p=structure(sample,{axis:'rows',type:'move',index:1,direction:1});assert.equal(p.rows[2].id,'r2');assert.equal(associations(p,'r2','c1')[0].label,'Practice');assert.deepEqual(p.rows[2].values,sample.rows[1].values);});
test('invalid structure operations fail without mutating input',()=>{const original=structuredClone(sample);for(const action of [{axis:'bad',type:'add'},{axis:'rows',type:'unknown'},{axis:'columns',type:'remove',index:1.5}])assert.throws(()=>structure(sample,action));assert.deepEqual(sample,original);});
test('example JSON files match executable fixtures',async()=>{for(const [name,value]of Object.entries({sample,small}))assert.deepEqual(parseProject(await readFile(`examples/${name}.json`,'utf8')),value);});
test('formula-looking TSV cells stay text and HTML remains inert',()=>{const p=parseTSV('Item\tValue\nA\t=1+1\nB\t<script>alert(1)</script>');assert.equal(p.rows[0].values[0],'=1+1');assert.match(exportHTML(p),/&lt;script&gt;alert\(1\)&lt;\/script&gt;/);assert.equal(parseProject(toJSON(p)).rows[1].values[0],'<script>alert(1)</script>');});

test('split print styling prefers whole tables without disabling grouped pagination',()=>{const split=exportHTML(sample,'split'),grouped=exportHTML(sample,'grouped');assert.match(split,/<div class="table-wrap split-output">/);assert.match(grouped,/<div class="table-wrap grouped-output">/);assert.match(split,/table\{break-inside:auto\}\.split-output table\{break-inside:avoid-page;page-break-inside:avoid\}/);assert.match(split,/caption\{font-size:13px;break-after:avoid-page\}/);});

test('split print context is escaped in an attribute without changing header labels',()=>{const p=structuredClone(sample);p.caption='Context <b> & "quote"';const html=exportHTML(p,'split');assert.match(html,/data-print-caption="Context &lt;b&gt; &amp; &quot;quote&quot; \/ Foundations \/ Morning">Session<\/th>/);assert.match(html,/content:attr\(data-print-caption\)/);});
