import {validateProject,blocks,associations} from './core.mjs';
export const escapeHTML=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const e=escapeHTML;
export const toJSON=input=>JSON.stringify(validateProject(input),null,2)+'\n';
export function exportFragment(input,mode='grouped'){
 const p=validateProject(input);if(!['grouped','split'].includes(mode))throw new Error('Export mode must be grouped or split');
 if(mode==='split')return blocks(p.rowGroups,p.rows.length).flatMap((rg,ri)=>blocks(p.columnGroups,p.columns.length).map((cg,ci)=>{
  const prefix=`${p.id}-s-${ri}-${ci}`,cols=p.columns.slice(cg.start,cg.start+cg.span),rows=p.rows.slice(rg.start,rg.start+rg.span),caption=[p.caption,rg.label,cg.label].filter(Boolean).join(' / ');
  return `<table id="${prefix}"><caption>${e(caption)}</caption><thead><tr><th scope="col" data-print-caption="${e(caption)}">${e(p.rowHeaderLabel)}</th>${cols.map(c=>`<th id="${prefix}-c-${c.id}" scope="col">${e(c.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th id="${prefix}-r-${r.id}" scope="row">${e(r.label)}</th>${cols.map((c,j)=>`<td id="${prefix}-v-${r.id}:${c.id}" data-row="${r.id}" data-col="${c.id}" headers="${prefix}-r-${r.id} ${prefix}-c-${c.id}">${e(r.values[cg.start+j])}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 })).join('\n');
 const prefix=p.id+'-g',cg=blocks(p.columnGroups,p.columns.length),rg=blocks(p.rowGroups,p.rows.length),hasCG=p.columnGroups.length>0,hasRG=p.rowGroups.length>0,stub=hasRG?2:1;
 const colgroups=`<colgroup span="${stub}"></colgroup>`+cg.map(g=>`<colgroup span="${g.span}"></colgroup>`).join('');
 const head=`<thead><tr>${hasRG?`<th scope="col"${hasCG?' rowspan="2"':''}>${e(p.rowGroupLabel)}</th>`:''}<th scope="col"${hasCG?' rowspan="2"':''}>${e(p.rowHeaderLabel)}</th>${hasCG?cg.map(g=>`<th id="${prefix}-cg-${g.id}" scope="colgroup" colspan="${g.span}">${e(g.label)}</th>`).join(''):p.columns.map(c=>`<th id="${prefix}-c-${c.id}" scope="col">${e(c.label)}</th>`).join('')}</tr>${hasCG?`<tr>${p.columns.map(c=>`<th id="${prefix}-c-${c.id}" scope="col">${e(c.label)}</th>`).join('')}</tr>`:''}</thead>`;
 const bodies=rg.map(g=>`<tbody>${p.rows.slice(g.start,g.start+g.span).map((r,i)=>`<tr>${hasRG&&i===0?`<th id="${prefix}-rg-${g.id}" scope="rowgroup" rowspan="${g.span}">${e(g.label)}</th>`:''}<th id="${prefix}-r-${r.id}" scope="row">${e(r.label)}</th>${p.columns.map((c,j)=>`<td id="${prefix}-v-${r.id}:${c.id}" data-row="${r.id}" data-col="${c.id}" headers="${associations(p,r.id,c.id).map(h=>h.id).join(' ')}">${e(r.values[j])}</td>`).join('')}</tr>`).join('')}</tbody>`).join('');
 return `<table id="${prefix}"><caption>${e(p.caption)}</caption>${colgroups}${head}${bodies}</table>`;
}
export function exportHTML(input,mode='grouped',language='en'){
 const p=validateProject(input),fragment=exportFragment(p,mode),ja=language==='ja';
 const notice=ja?'HeaderMap が生成した関連見出しです。スクリーンリーダーの読み上げ方や WCAG・法的適合を保証しません。実際の掲載先と支援技術で検証してください。':'HeaderMap generates explicit header associations. It does not guarantee screen-reader behavior, WCAG conformance, or legal compliance. Review in your actual publishing context and assistive technology.';
 return `<!doctype html><html lang="${ja?'ja':'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>${e(p.caption)} · HeaderMap</title><style>body{font:15px/1.6 system-ui,sans-serif;margin:28px;color:#24324a}main{max-width:1100px;margin:auto}h1{font-size:25px;overflow-wrap:anywhere}.notice{padding:14px;border:1px solid #bdc8da;background:#f2f5f9;font-size:12px}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;margin:24px 0;table-layout:fixed}caption{text-align:left;font-weight:700;padding:12px 0;overflow-wrap:anywhere}th,td{border:1px solid #b5c1d2;text-align:left;padding:10px;overflow-wrap:anywhere;white-space:pre-wrap}th{background:#edf1f7}th[scope=colgroup],th[scope=rowgroup]{background:#dfe8f5}td{background:#fff}thead{display:table-header-group}tr{break-inside:avoid}@media print{body{margin:0;font-size:9px}th,td{padding:5px}.table-wrap{overflow:visible}table{break-inside:auto}.split-output table{break-inside:avoid-page;page-break-inside:avoid}.split-output thead th:first-child::before{content:attr(data-print-caption);display:block;font-size:8px;font-weight:normal;line-height:1.35;margin-bottom:5px}caption{font-size:13px;break-after:avoid-page}h1{font-size:20px}}@page{size:A4 landscape;margin:12mm}</style></head><body><main><h1>${e(p.caption)}</h1><p class="notice">${e(notice)}</p><div class="table-wrap ${mode==='split'?'split-output':'grouped-output'}">${fragment}</div></main></body></html>\n`;
}
